In [1]:
import pandas as pd
df = pd.read_csv("smart_phone_usage_and_productivity.csv")
df.head()

,Users,Age,Gender,Occupation,level of Student (If Student),Region,Smartphone owner,SmartPhone duration?,Smartphone daily,Smartphone usage Select all that apply,...,Efficiency Of Phone,Use Productive Apps,Productive Applications,Smartphone Distraction Frequency,Productivity Affecting Activities,Smartphone Productivity Impact,Smartphone Usage Impact,Smartphone Usage Management Strategies,Productivity Usage Challenges,Productivity Improvement Suggestions
0,1.0,18-25,Female,Student,Undergraduate,Bafoussam,Yes,4-6 years,More than 8 hours,"Communication (calls, messages);Social Media;E...",...,Very much,Yes,AI tools,Often,Messaging,Strongly agree,"Yes, positively",I do not manage my usage,Always interrupted by messages,NaN
1,2.0,18-25,Female,Self-employed,Not Applicable,Bamenda,Yes,More than 6 years,More than 8 hours,Online Shopping;Banking/financial services;Com...,...,Extremely,Yes,Google Calendar;Notes applications;Microsoft O...,Always,Messaging,Strongly agree,"Yes, positively",Setting screen time limits;Keeping the phone a...,Notifications alway pop,NaN
2,3.0,Under 18,Female,Student,Undergraduate,West,Yes,1-3 years,More than 8 hours,"Communication (calls, messages);Social Media;E...",...,Very much,Yes,Google Calendar;Microsoft Office/Google Worksp...,Sometimes,Social media,Agree,"Yes, positively",Turning off notifications,Distraction,Less notifications
3,4.0,18-25,Female,Student,Undergraduate,Littoral,Yes,4-6 years,More than 8 hours,"Communication (calls, messages);Social Media;E...",...,Very much,Yes,Google Calendar;Notes applications;Microsoft O...,Sometimes,Social media,Agree,"Yes, positively",Keeping the phone away while working/Studying;...,Distraction from incoming messages and social ...,An easy way of restricting the usage of some a...
4,5.0,18-25,Male,Student,Undergraduate,Northwest region,Yes,4-6 years,More than 8 hours,"Communication (calls, messages);Social Media;E...",...,Very much,No,NaN,Always,Social media,Strongly disagree,"Yes, negatively",Keeping the phone away while working/Studying,Distracting notifications,NaN

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 24 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Users                                   35 non-null     float64
 1   Age                                     35 non-null     str
 2   Gender                                  35 non-null     str
 3   Occupation                              35 non-null     str
 4   level of Student (If Student)           32 non-null     str
 5   Region                                  33 non-null     str
 6   Smartphone owner                        36 non-null     str
 7   SmartPhone duration?                    35 non-null     str
 8   Smartphone daily                        35 non-null     str
 9   Smartphone usage Select all that apply  35 non-null     str
 10  Applications frquently use              35 non-null     str
 11  Daily phone check                       35 non-null     str
 12  Productive Usage                        35 non-null     str
 13  Activities Using Phone                  35 non-null     str
 14  Efficiency Of Phone                     35 non-null     str
 15  Use Productive Apps                     35 non-null     str
 16  Productive Applications                 30 non-null     str
 17  Smartphone Distraction Frequency        35 non-null     str
 18  Productivity Affecting Activities       35 non-null     str
 19  Smartphone Productivity Impact          35 non-null     str
 20  Smartphone Usage Impact                 35 non-null     str
 21  Smartphone Usage Management Strategies  35 non-null     str
 22  Productivity Usage Challenges           35 non-null     str
 23  Productivity Improvement Suggestions    25 non-null     str
dtypes: float64(1), str(23)
memory usage: 6.9 KB

In [3]:
df.describe()

           Users
count  35.000000
mean   18.000000
std    10.246951
min     1.000000
25%     9.500000
50%    18.000000
75%    26.500000
max    35.000000

In [4]:
df.columns

Index(['Users', 'Age', 'Gender', 'Occupation', 'level of Student (If Student)',
       'Region', 'Smartphone owner', 'SmartPhone duration?',
       'Smartphone daily', 'Smartphone usage Select all that apply',
       'Applications frquently use', 'Daily phone check', 'Productive Usage ',
       'Activities Using Phone', 'Efficiency Of Phone', 'Use Productive Apps',
       'Productive Applications', 'Smartphone Distraction Frequency',
       'Productivity Affecting Activities', 'Smartphone Productivity Impact',
       'Smartphone Usage Impact', 'Smartphone Usage Management Strategies',
       'Productivity Usage Challenges',
       'Productivity Improvement Suggestions'],
      dtype='str')

In [5]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace (" ", "_")

In [6]:
df.columns

Index(['users', 'age', 'gender', 'occupation', 'level_of_student_(if_student)',
       'region', 'smartphone_owner', 'smartphone_duration?',
       'smartphone_daily', 'smartphone_usage_select_all_that_apply',
       'applications_frquently_use', 'daily_phone_check', 'productive_usage_',
       'activities_using_phone', 'efficiency_of_phone', 'use_productive_apps',
       'productive_applications', 'smartphone_distraction_frequency',
       'productivity_affecting_activities', 'smartphone_productivity_impact',
       'smartphone_usage_impact', 'smartphone_usage_management_strategies',
       'productivity_usage_challenges',
       'productivity_improvement_suggestions'],
      dtype='str')

In [7]:
df = df.rename(columns = {"level_of_student_(if_student)" : "level_of_student"})

In [8]:
df.columns

Index(['users', 'age', 'gender', 'occupation', 'level_of_student', 'region',
       'smartphone_owner', 'smartphone_duration?', 'smartphone_daily',
       'smartphone_usage_select_all_that_apply', 'applications_frquently_use',
       'daily_phone_check', 'productive_usage_', 'activities_using_phone',
       'efficiency_of_phone', 'use_productive_apps', 'productive_applications',
       'smartphone_distraction_frequency', 'productivity_affecting_activities',
       'smartphone_productivity_impact', 'smartphone_usage_impact',
       'smartphone_usage_management_strategies',
       'productivity_usage_challenges',
       'productivity_improvement_suggestions'],
      dtype='str')

In [9]:
 df = df.rename(columns = {"smartphone_duration?" : "smartphone_duration"})
 df = df.rename(columns = {"smartphone_usage_select_all_that_apply" : "smartphone_usage"})

In [10]:
df.columns

Index(['users', 'age', 'gender', 'occupation', 'level_of_student', 'region',
       'smartphone_owner', 'smartphone_duration', 'smartphone_daily',
       'smartphone_usage', 'applications_frquently_use', 'daily_phone_check',
       'productive_usage_', 'activities_using_phone', 'efficiency_of_phone',
       'use_productive_apps', 'productive_applications',
       'smartphone_distraction_frequency', 'productivity_affecting_activities',
       'smartphone_productivity_impact', 'smartphone_usage_impact',
       'smartphone_usage_management_strategies',
       'productivity_usage_challenges',
       'productivity_improvement_suggestions'],
      dtype='str')

In [11]:
efficiency_mapping = {"Not at all":"0", "Slightly" :"1", "Moderately": "2", "Very much": "3", "Extremely": "4"}
df["phone_efficiency"] = df["efficiency_of_phone"].map(efficiency_mapping)

In [12]:
df[["efficiency_of_phone","phone_efficiency"]].head()

  efficiency_of_phone phone_efficiency
0           Very much                3
1           Extremely                4
2           Very much                3
3           Very much                3
4           Very much                3

In [13]:
productivity_impact_mapping = {"Strongly disagree": "1", "Disagree": "2", "Neutral": "3", "Agree": "4", "Strongly agree": "5"}
df["productivity_impact"] = df["smartphone_productivity_impact"].map(productivity_impact_mapping)

In [14]:
df[["smartphone_productivity_impact" , "productivity_impact"]].head()

  smartphone_productivity_impact productivity_impact
0                 Strongly agree                   5
1                 Strongly agree                   5
2                          Agree                   4
3                          Agree                   4
4              Strongly disagree                   1

In [15]:
df.isnull().sum()

users                                      1
age                                        1
gender                                     1
occupation                                 1
level_of_student                           4
region                                     3
smartphone_owner                           0
smartphone_duration                        1
smartphone_daily                           1
smartphone_usage                           1
applications_frquently_use                 1
daily_phone_check                          1
productive_usage_                          1
activities_using_phone                     1
efficiency_of_phone                        1
use_productive_apps                        1
productive_applications                    6
smartphone_distraction_frequency           1
productivity_affecting_activities          1
smartphone_productivity_impact             1
smartphone_usage_impact                    1
smartphone_usage_management_strategies     1
productivity_usage_challenges              1
productivity_improvement_suggestions      11
phone_efficiency                           1
productivity_impact                        1
dtype: int64

In [16]:
df["productivity_impact"] = df["productivity_impact"].fillna(
    df["productivity_impact"].mode()[0]
)

In [17]:
df["productivity_impact"].dtype

In [18]:
df["productivity_impact"]

0     5
1     5
2     4
3     4
4     1
5     4
6     5
7     4
8     4
9     3
10    5
11    4
12    3
13    3
14    2
15    5
16    4
17    5
18    3
19    3
20    3
21    4
22    4
23    3
24    5
25    4
26    3
27    5
28    4
29    3
30    3
31    4
32    4
33    4
34    5
35    4
Name: productivity_impact, dtype: str

In [19]:
categorical_cols = df.select_dtypes(include="str").columns

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [20]:
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [21]:
df.isnull().sum()

users                                     0
age                                       0
gender                                    0
occupation                                0
level_of_student                          0
region                                    0
smartphone_owner                          0
smartphone_duration                       0
smartphone_daily                          0
smartphone_usage                          0
applications_frquently_use                0
daily_phone_check                         0
productive_usage_                         0
activities_using_phone                    0
efficiency_of_phone                       0
use_productive_apps                       0
productive_applications                   0
smartphone_distraction_frequency          0
productivity_affecting_activities         0
smartphone_productivity_impact            0
smartphone_usage_impact                   0
smartphone_usage_management_strategies    0
productivity_usage_challenges             0
productivity_improvement_suggestions      0
phone_efficiency                          0
productivity_impact                       0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
from sqlalchemy import create_engine
username = "postgres"
password = "123"     
host = "localhost"
port = "5432"
database = "Smartphone_Usage_and_Productivity"
engine = create_engine( f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
table_name = "smartphone_usage_and_productivity"
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database {database}.")

Data successfully loaded into table 'smartphone_usage_and_productivity' in database Smartphone_Usage_and_Productivity.